[build]
  publish = "public"
  command = ""

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Cache-Control = "public, max-age=600"

# Allow embedding YouTube/Spotify iframes
[[headers]]
  for = "/music.html"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.youtube.com https://www.youtube-nocookie.com https://www.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data:; font-src 'self' https://fonts.gstatic.com; frame-src 'self' https://www.youtube.com https://open.spotify.com; connect-src 'self'"
